### DISCUSSION TITLE
Lenovo Thinkpads (various)

### DISCUSSION THREAD

**Discussion by ghost** [vmatare/thinkfan#121] [Community Configs]
- Tested on Thinkpad T520
- Driven by the [coretemp sensor](https://www.kernel.org/doc/html/latest/hwmon/coretemp.html)
- Name-based sensor search (robust against sensor indices changing by module load order)
- Fan overdrive above 80°C (via the `thinkpad_acpi` kernel module)
- Ignores all but the highest temperature across all sensors

```yaml
sensors:
  - hwmon: /sys/class/hwmon  
    name: coretemp
    indices: [1, 2, 3, 4, 5]
  - hwmon: /sys/class/hwmon                                         
    name: acpitz
    indices: [1]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0,      0,     55]
  - [1,     48,     60]
  - [2,     50,     61]
  - [3,     52,     63]
  - [4,     56,     67]
  - [5,     59,     70]
  - [7,     63,     80]
  - [127,   75,     32767]
```

**Comment by dkowis** [comment]
* For my ThinkPad T15p Gen 1
* driven by the thermal zone sensor that monitors the CPU.
    * I didn't use the coretemp directly, because the fan would change speeds *all the time*. Using the thermal zone smoothed the fan change thresholds, as it took longer for that sensor to cool off and to heat up.
* name based sensor search (same reasons as above)
* fan overdrive at 78C (uses the `thinkpad_acpi` module)

```yaml
# Thinkfan configuration for a ThinkPad T15p Gen 1

sensors:
  - hwmon: /sys/class/hwmon
    name: thinkpad
    indices: [1]
  - nvml: 01:00.0
fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
   - [0, 0, 40]
   - [1, 37, 53]
   - [2, 50, 58]
   - [3, 56, 68]
   - [4, 65, 75]
   - [5, 73, 78]
   - ["level full-speed", 77, 32767]
```
