### DISCUSSION TITLE
Desktop Systems

### DISCUSSION THREAD

**Discussion by vmatare** [vmatare/thinkfan#153] [Community Configs]
# MSI X470 Gaming Pro
- AMD GPU (1 sensor, 1 fan)
- AMD CPU (1 sensor)
- NCT6795 (2 sensors, 6 fans)

```yaml
################################################################
# This is an example config for a large PC with multiple
# fans and temperature sensors.
#
# It reads temperatures from the GPU, CPU and mainboard
# and controls the GPU fan, the CPU fan, and 4 case fans
################################################################

sensors:
  - hwmon: /sys/class/hwmon
    name: amdgpu
    indices:
    - 1 # GPU temperature
  - hwmon: /sys/class/hwmon
    name: k10temp
    indices: 
    - 2 # CPU temperature
  - hwmon: /sys/class/hwmon
    name: nct6795
    indices:
    - 1 # System temperature
    - 3 # Power Converter temperature

fans:
  - hwmon: /sys/class/hwmon
    name: amdgpu
    indices:
      - 1 # GPU fan
    levels:
        # The GPU fan only affects the temperature of the GPU,
        # so ignore all other sensors here.
      - speed: 0
        upper_limit: [58, _, _, _]
      - speed: 50
        lower_limit: [46, _, _, _]
        upper_limit: [59, _, _, _]
      - speed: 80
        lower_limit: [50, _, _, _]
        upper_limit: [69, _, _, _]
      - speed: 110
        lower_limit: [60, _, _, _]
        upper_limit: [73, _, _, _]
      - speed: 130
        lower_limit: [65, _, _, _]
        upper_limit: [78, _, _, _]
      - speed: 179
        lower_limit: [70, _, _, _]
        upper_limit: [83, _, _, _]
      - speed: 210
        lower_limit: [75, _, _, _]
        upper_limit: [87, _, _, _]
      - speed: 255
        lower_limit: [79, _, _, _]

  - hwmon: /sys/class/hwmon
    name: nct6795
    indices: [1] # PUMP fan @GPU
    levels:
        # This case fan directly supplies the GPU with fresh air, so consider GPU temps only.
      - speed: 0
        upper_limit: [51, _, _, _]
      - speed: 80
        lower_limit: [44, _, _, _]
        upper_limit: [52, _, _, _]
      - speed: 100
        lower_limit: [45, _, _, _]
        upper_limit: [56, _, _, _]
      - speed: 110
        lower_limit: [49, _, _, _]
        upper_limit: [59, _, _, _]
      - speed: 120
        lower_limit: [54, _, _, _]
        upper_limit: [64, _, _, _]
      - speed: 140
        lower_limit: [60, _, _, _]
        upper_limit: [67, _, _, _]
      - speed: 180
        lower_limit: [64, _, _, _]
        upper_limit: [73, _, _, _]
      - speed: 210
        lower_limit: [69, _, _, _]


  - hwmon: /sys/class/hwmon
    name: nct6795
    indices:
      - 2 # CPU fan
    levels:
        # Same as above for the CPU fan, i.e.
        # look only at the CPU temperature
      - speed: 70
        upper_limit: [_, 54, _, _]
      - speed: 90
        lower_limit: [_, 48, _, _]
        upper_limit: [_, 62, _, _]
      - speed: 110
        lower_limit: [_, 57, _, _]
        upper_limit: [_, 65, _, _]
      - speed: 140
        lower_limit: [_, 61, _, _]
        upper_limit: [_, 68, _, _]
      - speed: 180
        lower_limit: [_, 65, _, _]
        upper_limit: [_, 75, _, _]
      - speed: 255
        lower_limit: [_, 69, _, _]

  - hwmon: /sys/class/hwmon
    name: nct6795
    indices:
      - 3 # back case fan
      - 4 # top front case fan
      - 5 # top back case fan
      - 6 # front case fan
    levels:
        # The case fans on the other hand affect the ambient temperature
        # for both the GPU and the CPU fan, so their config depends on
        # all the temperatures we know.
      - speed: [0,  0,  0,  0]
        upper_limit:            [44, 54, 45, 49]
      - speed: [0,  70, 70, 80]
        lower_limit:            [40, 38, 40, 45]
        upper_limit:            [45, 58, 46, 50]
      - speed: [0,  80, 80, 90]
        lower_limit:            [44, 46, 44, 48]
        upper_limit:            [47, 62, 48, 54]
      - speed: [40, 90, 90, 100]
        lower_limit:            [45, 50, 46, 50]
        upper_limit:            [49, 66, 54, 58]
      - speed: [50, 115, 115, 125]
        lower_limit:            [47, 56, 52, 56]
        upper_limit:            [55, 68, 58, 64]
      - speed: [50, 120, 120, 130]
        lower_limit:            [52, 58, 56, 58]
        upper_limit:            [64, 72, 60, 68]
      - speed: [75, 170, 170, 180]
        lower_limit:            [60, 62, 58, 64]
        upper_limit:            [68, 74, 62, 70]
      - speed: [85, 180, 180, 190]
        lower_limit:            [64, 66, 60, 66]
        upper_limit:            [72, 76, 64, 74]
      - speed: [100, 210, 210, 220]
        lower_limit:            [70, 72, 62, 70]
        upper_limit:            [76, 78, 66, 76]
      - speed: [180, 255, 255, 255]
        lower_limit:            [74, 74, 64, 74]
        upper_limit:            [80, 82, 70, 78]
      - speed: [255, 255, 255, 255]
        lower_limit:            [78, 79, 68, 76]
```
