### DISCUSSION TITLE
[ThinkPad E540] Thinkfan change the levels, but not the actual speed

### DISCUSSION THREAD

**Discussion by Drommer** [vmatare/thinkfan#252] [Specific Hardware]
I think the problem is more with the driver than with thinkfan itself. However, maybe someone has encountered the same problem and can help.

I have set up getting the temperature from the sensors and changing the level in `/proc/acpi/ibm/fan`, but it has no effect on the actual speed, at any level I have `speed: 0`.

`/etc/thinkfan.conf`:
```
sensors:
  - hwmon: /sys/class/hwmon
    name: coretemp
    indices: [1]

  - hwmon: /sys/class/hwmon
    name: acpitz
    indices: [1]

  - nvml: 01:00.0
    optional: true

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - speed: 0
    upper_limit: [50, 50, 50]

  - speed: 3
    lower_limit: [45, 45, 45]
    upper_limit: [65, 65, 65]

  - speed: 7
    lower_limit: [55, 55, 55]
    upper_limit: [75, 75, 75]

  - speed: "level full-speed"
    lower_limit: [65, 65, 65]
    upper_limit: [90, 90, 90]
```

`systemctl status thinkfan`:
```
thinkfan[465]: Temperatures(bias): 66(0), 67(0), 0(0) -> Fans: level 7
thinkfan[465]: Temperatures(bias): 52(0), 54(0), 0(0) -> Fans: level 3
```

`/proc/acpi/ibm/fan`
```
status: enabled
speed: 0
level: 3
commands: level <level> (<level> is 0-7, auto, disengaged, full-speed)
```

I also create the file `/etc/modprobe.d/thinkpad_acpi.conf` with line
```
options thinkpad_acpi experimental=1 fan_control=1
```

I use Arch Linux, thinkfan compiled from master branch. What am I doing wrong?
