### ISSUE TITLE
Autostart fails, and restart is needed because hwmon is not found

### ISSUE THREAD

**Issue by lakotamm** [vmatare/thinkfan#118]
Hello,
For the last few days, I have been experiencing issues with thinkfan failing to start, because it cannot find hwmon.

OS: Manjaro Linux x86_64 - testing branch
Host: ThinkPad T490
Kernel: 5.9.12-1-MANJARO 
CPU: Intel i7-8565U 

<pre><font color="#CC0000"><b>●</b></font> thinkfan.service - simple and lightweight fan control program
     Loaded: loaded (/usr/lib/systemd/system/thinkfan.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/thinkfan.service.d
             └─override.conf
     Active: <font color="#CC0000"><b>failed</b></font> (Result: exit-code) since Tue 2020-12-15 21:58:42 CET; 1h 25min ago
    Process: 520 ExecStart=/usr/bin/thinkfan $THINKFAN_ARGS <font color="#CC0000"><b>(code=exited, status=1/FAILURE)</b></font>

Dec 15 21:58:42 miroslav-20n2cto1ww systemd[1]: Starting simple and lightweight fan control program...
Dec 15 21:58:42 miroslav-20n2cto1ww thinkfan[520]: <font color="#CC0000"><b>ERROR: Error scanning /sys/devices/platform/coretemp.0/hwmon: No such file or directory</b></font>
Dec 15 21:58:42 miroslav-20n2cto1ww systemd[1]: <b>thinkfan.service: Control process exited, code=exited, status=1/FAILURE</b>
Dec 15 21:58:42 miroslav-20n2cto1ww systemd[1]: <font color="#D7D75F"><b>thinkfan.service: Failed with result &apos;exit-code&apos;.</b></font>
Dec 15 21:58:42 miroslav-20n2cto1ww systemd[1]: <font color="#CC0000"><b>Failed to start simple and lightweight fan control program.</b></font>
</pre>

thinkfan.yaml:

```
sensors:
  - hwmon: /sys/devices/platform/coretemp.0/hwmon
    indices: [2, 3, 4, 5]

levels:
  - [0, 0 , 55]
  - [1, 50, 60]
  - [2, 55, 65]
  - [3, 60, 70]
  - [4, 65, 75]
  - [5, 70, 80]
  - [6, 75, 85]
  - [7, 80, 32767]
```
Since restarting the service fixes the issue, I assume that hwmon is initialized after thinkfan. Is this a more widespread issue or just me having messed up configuration?
Thanks for the help!
