### ISSUE TITLE
1.2.2: Endless loop on non-existent hwmon index

### ISSUE THREAD

**Issue by lakotamm** [vmatare/thinkfan#145]
Hello. A few weeks ago, the thinkfan fan control stopped working on my laptop. Today I finally found time to investigate the error. Here are my findings:

Symptoms: The fan control simply does not run. In the best case, the program reports temperature once and stays there, requiring a restart to report anything else. In the worst case (when I choose a non-existing sensor in the .yaml in the config) in straight out freezes.

The issue gets resolved when I compile and install and earlier version of thinkfan.

Thinkfan version: 1.2.2
Tested functioning earlier versions: 1.2.1, 1.1,
Tested effected kernels: 5.13 (Fedora 34, Manjaro), 5.12 (Fedora 34, Manjaro), 5.4 (Manjaro)
Laptop: T490 with BIOS 1.53, i7-8565U and dGPU MX250

I am having hard times finding any debugging information to provide.
systemctl reports:
`Jul 29 01:10:31 fedora systemd[1]: Starting Thinkfan, the minimalist fan control program...
`
My config is:

```yaml
sensors:
  - hwmon: /sys/devices/platform/coretemp.0/hwmon
    indices: [2, 3, 4, 5]

levels:
  - [0, 0, 55]
  - [1, 48, 62]
  - [2, 55, 69]
  - [3, 60, 74]
  - [4, 65, 80]
  - [5, 71, 84]
  - [6, 77, 89]
  - [7, 82, 32767]
```

Chanking the indices to 
` indices: [1,2, 3, 4, 5, 6]` (6 does not exists) results in a complete freeze of the process, which cannot be ended in a normal way.
