### ISSUE TITLE
ERROR: No fans are configured in /etc/thinkfan.conf

### ISSUE THREAD

**Issue by cgirerd** [vmatare/thinkfan#155]
Hello,
Thank you very much for this software! I just downloaded and compiled the code of the master branch. I installed it on my ThinkPad P53 running Debian 11. I ran thinkfan using the command `thinkfan -n` and got the following error:
`ERROR: No fans are configured in /etc/thinkfan.conf`
However, the fans seem to be configured correctly in /etc/thinkfan.conf I think. Here is the content of this file:

```
sensors:

  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon
    name: thinkpad
    indices: [1, 2, 3, 4, 5, 6, 7, 8]

  - hwmon: /sys/devices/platform/coretemp.0/hwmon
    name: coretemp
    indices: [1, 2, 3, 4, 5, 6, 7]

  - hwmon: /sys/devices/pci0000:00/0000:00:1b.0/0000:02:00.0/hwmon
    name: nvme
    indices: [1, 2]

  - hwmon: /sys/devices/pci0000:00/0000:00:1d.0/0000:55:00.0/hwmon
    name: nvme
    indices: [1, 2]

  - hwmon: /sys/devices/virtual/thermal/thermal_zone0/hwmon0
    name: acpitz
    indices: [1]

  - hwmon: /sys/devices/virtual/thermal/thermal_zone9
    name: iwlwifi_1
    optional: true
    indices: [1]

  - hwmon: /sys/devices/virtual/thermal/thermal_zone6
    name: pch_cannonlake
    indices: [1]

  - nvml: 01:00.0

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0, 55]
  - [1, 50, 60]
  - [2, 57, 63]
  - [3, 60, 66]
  - [4, 63, 69]
  - [5, 66, 72]
  - [6, 69, 75]
  - [7, 72, 32767]
```
I would be happy to have any hint on this issue... :)
