### ISSUE TITLE
Found multiple hwmons with this name "nvme"

### ISSUE THREAD

**Issue by koutheir** [vmatare/thinkfan#156]
I configured my `thinkfan.yaml` to take into account the NVME temperatures like follows:
```yaml
sensors:
  - hwmon: /sys/class/hwmon
    name: nvme
    indices: [2, 3]
    correction: [0, 0]
```

But running `thinkfan -nv` issues this error:
```
ERROR: /etc/thinkfan.conf:37:
    name: nvme
          ^
Found multiple hwmons with this name:  /sys/class/hwmon/hwmon2 /sys/class/hwmon/hwmon1.
```

And it is true that both `/sys/class/hwmon/hwmon1/name` and `/sys/class/hwmon/hwmon2/name` have the same contents, even though they correspond to the two distinct NVME slots on the mother board.

How can I solve this issue?
