### ISSUE TITLE
Thinkpad T14s: Fan keeps running during suspend

### ISSUE THREAD

**Issue by JunnanZ** [vmatare/thinkfan#181]
Output from `systemctl status thinkfan` before and after suspend:
```
Apr 06 15:35:09 thinkpad thinkfan[262008]: Temperatures(bias): 53(0) -> Fans: level 3
Apr 06 15:36:33 thinkpad thinkfan[262008]: Going to sleep: Will allow sensor read errors for the next 4 loops.
Apr 06 15:36:49 thinkpad thinkfan[262008]: Received SIGUSR2: Re-initializing fan control.
Apr 06 15:36:49 thinkpad thinkfan[262008]: Temperatures(bias): 49(0) -> Fans: level 2
```
The fan keeps running at the same speed during suspend.

**Comment by vmatare** [comment]
Hi @JunnanZ, do you actually mean that the fan keeps running **during** suspend? I.e. your laptop completely turns off (screen, CPU, hard disk etc.) but the fan keeps running? In that case, you have faulty hardware because thinkfan has no influence whatsoever on what happens **during suspend**.

Or did you mean the switch to `level 2` **after waking up from suspend** has no effect and the fan stays at level 3? In that case please post your config file and the output of `cat /proc/acpi/ibm/thermal` before and after suspending.

**Comment by tante** [comment]
I have the same issue (Thinkpad T14s Gen3, Intel): When I close the lid with the fan running it will keep running forever, as soon as I open the lid (given I waited a short time), thinkfan kicks in, sees the temperature being down and shuts down the fan.

When I have no thinkfan running and things being on "auto" it doesn't happen.

I wonder if it would be possible to shift to auto upon suspend but I don't know how feasible it is to get that signal into thinkfan. I'll add my configuration as soon as I get home.

**Comment by tante** [comment]
My thinkfan.conf:

```
sensors:
  - tpacpi: /proc/acpi/ibm/thermal
    indices: [1, 3, 5, 6, 7]

fans:
  - tpacpi: /proc/acpi/ibm/fan


levels:
  - [0,	0,	53]
  - [1,	46,	60]
  - [2,	58,	65]
  - [3,	62,	70]
  - [4,	68,	75]
  - [5,	73,	80]
  - [6,	78,	85]
  - [7,	85,	32767]
```
