### ISSUE TITLE
Issue when applying mode to pwm

### ISSUE THREAD

**Issue by berrabe** [vmatare/thinkfan#191]
### ISSUE
---
IDK why, but thinkfan on my laptop do weird things. Thinkfan success read temp and choose right level mode, but when choosen mode applied to fan conf file, it's wrong. For example for temp under 50 °C set to level 1, thinkfan know that and show level 1 (3.xxx RPM) on log, but the reality on fan site is level 0 (0 RPM)

&nbsp;

### PoC
---
tested on **ThinkPad X240** with **manjaro 21.3.2 (ruah)**, and **thinkfan 1.3.1 (AUR)**

here's my thinkfan conf file

```yml
# created by berrabe (ThinkPad X240)
# references:
#   - minimal_conf: |
#     sed -E 's/^ *#.*$//g; /^$/d' /usr/share/doc/thinkfan/examples/thinkfan.yaml
#   - docs: |
#     https://wiki.archlinux.org/title/fan_speed_control#ThinkPad_laptops
#     man thinkpad.conf
#     thinkfan github issue 45 and 146
---
sensors:
  - hwmon: /sys/class/hwmon/hwmon3/temp1_input
  # - hwmon: /sys/class/hwmon
  #   name: thinkpad
  #   indices: [1]
fans:
  # - hwmon: /sys/class/hwmon/hwmon3/pwm1
  - tpacpi: /proc/acpi/ibm/fan
levels:
  - [0, 0, 40]
  - [1, 40, 50]
  - ["level auto", 50, 100]
```

and tested with `thinkfan -n`

![2022-07-07_13-25 edited](https://user-images.githubusercontent.com/34432326/177718900-ed6b9e5b-a65f-42b6-9680-5a42797a33d5.png)
