### ISSUE TITLE
/sys/class/hwmon/hwmonX is a directory

### ISSUE THREAD

**Issue by Foosec** [vmatare/thinkfan#203]
```yaml
fans:
  - tpacpi: /proc/acpi/ibm/fan

sensors:
  - hwmon: /sys/class/hwmon
    name: coretemp
    indicies: [1,2,3,4,5,6,7,8]

levels:
  - [1, 0,      40]
  - [3, 40,     60]
  - [4, 50,     60]
  - [5, 60,     70]
  - [6, 70,     75]
  - [7, 75,     85]
  - [127, 85, 100]
  ```

If im reading examples and docs right, this should find the driver with the name coretemp and use that, however:
```
foobar@foobars-thonkpad /s/c/hwmon> pwd
/sys/class/hwmon
foobar@foobars-thonkpad /s/c/hwmon> cat hwmon*/name
AC
acpitz
nvme
nvme
BAT0
pch_cannonlake
thinkpad
ucsi_source_psy_USBC000:001
coretemp
iwlwifi_1
ucsi_source_psy_USBC000:002
foobar@foobars-thonkpad /s/c/hwmon> sudo thinkfan

ERROR: Lost sensor read_temps_: Failed to read temperature(s) from /sys/class/hwmon/hwmon8: Is a directory
```
