### ISSUE TITLE
fan: tpacpi error: Invalid keyword in thinkfan V2.0.0

### ISSUE THREAD

**Issue by LloydS42** [vmatare/thinkfan#214]
I have made a upade from version 1.3.1 to 2.0.0. After that the keyword tpacpi is invalid in section fan in the config file.

```
$ sudo rc-service thinkfan start
 * Starting thinkfan ...
ERROR: /etc/thinkfan.conf:10:
  - tpacpi: /proc/acpi/ibm/fan
    ^
Invalid keyword.
 * start-stop-daemon: failed to start `/usr/sbin/thinkfan'
```

My thinkfan.conf:
```
sensors:
#  - chip: thinkpad-isa-0000
#    ids: [ CPU ]
#  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon5/temp1_input
#
  - tpacpi: /proc/acpi/ibm/thermal
    indices: [0]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - ["level auto", 20, 35]
  - ["level 1", 35, 40]
  - ["level 2", 40, 45]
  - ["level 3", 45, 55]
  - ["level 4", 55, 75]
  - ["level 5", 75, 85]
  - ["level 6", 85, 95]
  - ["level 7", 95, 255]
#  - ["full-speed", 100, 255]
```
