### ISSUE TITLE
thinkfan.service won't start

### ISSUE THREAD

**Issue by Guyv-dev** [vmatare/thinkfan#241]
Hi,
I have T14 gen3 and tried to work with Thinkfan, but I can't make it start. I am running pop_os.
my configs: 

/etc/modprobe.d/thinkfan.conf:
```
options thinkpad_acpi fan_control=1 experimental=1
```

/etc/thinkfan.conf:
```
sensors:
  # GPU
  - tpacpi: /proc/acpi/ibm/thermal
    indices: [1]
  # CPU
  - hwmon: /sys/class/hwmon
    name: coretemp
    indices: [2, 3, 4, 5]
  # Chassis
  - hwmon: /sys/class/hwmon
    name: thinkpad
    indices: [3, 5, 6, 7]
  # SSD
  - hwmon: /sys/class/hwmon
    name: nvme
    indices: [1, 2, 3]
    correction: [-5, 0, 0]
  # MB
  - hwmon: /sys/class/hwmon
    name: acpitz
    indices: [1]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0, 37]
  - [1, 35, 42]
  - [2, 40, 45]
  - [3, 43, 47]
  - [4, 45, 52]
  - [5, 50, 57]
  - [6, 55, 72]
  - [7, 70, 82]
  - ["level full-speed", 77, 32767]
```

/etc/default/thinkfan:
```
# Additional startup parameters
DAEMON_ARGS="-q"
THINKFAN_ARGS="-c /etc/thinkfan.conf"
```

cat /proc/acpi/ibm/fan:
```
status:		enabled
speed:		2626
level:		auto
commands:	level <level> (<level> is 0-7, auto, disengaged, full-speed)
commands:	enable, disable
commands:	watchdog <timeout> (<timeout> is 0 (off), 1-120 (seconds))
```

i am getting:
```
Apr 04 00:40:37 pop-os systemd[1]: Starting Thinkfan, the minimalist fan control program...
Apr 04 00:40:37 pop-os thinkfan[9759]: ERROR: /etc/thinkfan.conf:8:
                                           indices: [2, 3, 4, 5]
                                                    ^
                                       Unable to find requested temperature inputs in /sys/class/hwmon/hwmon6..
Apr 04 00:40:37 pop-os systemd[1]: thinkfan.service: Control process exited, code=exited, status=1/FAILURE
Apr 04 00:40:37 pop-os systemd[1]: thinkfan.service: Failed with result 'exit-code'.
Apr 04 00:40:37 pop-os systemd[1]: Failed to start Thinkfan, the minimalist fan control program.
```

/sys/devices -type f -name "temp*_input":
```
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp6_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp3_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp7_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp4_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp8_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp1_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp5_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon8/temp2_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp6_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp13_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp17_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp10_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp14_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp11_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp1_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp15_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp12_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp2_input
/sys/devices/platform/coretemp.0/hwmon/hwmon6/temp16_input
/sys/devices/pci0000:00/0000:00:06.0/0000:02:00.0/nvme/nvme0/hwmon3/temp3_input
/sys/devices/pci0000:00/0000:00:06.0/0000:02:00.0/nvme/nvme0/hwmon3/temp1_input
/sys/devices/pci0000:00/0000:00:06.0/0000:02:00.0/nvme/nvme0/hwmon3/temp2_input
/sys/devices/virtual/thermal/thermal_zone0/hwmon1/temp1_input
/sys/devices/virtual/thermal/thermal_zone9/hwmon7/temp1_inpu
```
