### ISSUE TITLE
Fan's keep running when putting laptop into sleep/suspend mode ThinkPad T14 Gen 4 i7-1335U

### ISSUE THREAD

**Issue by bremme** [vmatare/thinkfan#247]
I have a Lenovo ThinkPad T14 Gen 4 with a i7-1335U running Ubuntu 24.04 and I've compiled thinkfan from source. The tool seems to work fine, except for the fact that when I put the laptop into sleep the fans don't stop running. This makes sleep pretty unusable as you can imagine.

Maybe important to add this system only supports s2idle or S0 sleep. I've tried many things but could not get it to work properly. After much trial and error I found a workaround:

```shell
sudo systemctl edit thinkfan-sleep
# add the following line

[Service]
ExecStart=sh -c "echo 'disable' > /proc/acpi/ibm/fan"
```

I was a bit worried that this is potentially unsafe, but if I just watch ` /proc/acpi/ibm/fan` I see the fan's will be enabled automatically after waking from suspend so for me this workable I think.

But I was wondering why this happens in the first place and if there is no other proper way to fix it perhaps? In any case this workaround might be useful for other people struggling with the same issue.

**Comment by IvanSafonov** [comment]
I have the same laptop and the same problem. And it's thinkpad specific issue. It happens when you set manual levels like `level 1`. Bios for some reason does not turn it of afterwords. The only solution I have found is the same, change level before sleep. And I think it's safer to set `level auto`. There is a small chance that laptop won't enter sleep mode and the fan will be disabled for some time. The other problem is that now you have two concurrent level changes. Yesterday I'he pushed a new version of my own fan control service, and I think I [solved](https://github.com/IvanSafonov/fanctl/blob/main/conf/fanctl.yaml#L46-L48) this issue.

**Comment by jolars** [comment]
I believe this is a duplicate of https://github.com/vmatare/thinkfan/issues/181 I believe.

**Comment by OndraZizka** [comment]
Solution: I have installed `thinkfan`, set it up as a service, and then reset the bios - held a paper clip in a tiny hole at the left bottom of the laptop for 15 seconds. And also I've set the thermal temperature gradient. Now I enjoy the silence.

 ```
  185  sudo modprobe -r thinkpad_acpi && sudo modprobe thinkpad_acpi fan_control=1
  186  echo "level 0" | sudo tee /proc/acpi/ibm/fan

  148  sudo apt install thinkfan
  149  sudo nano /etc/modprobe.d/thinkpad_acpi.conf
   ## Contains only:  
   ##  options thinkpad_acpi fan_control=1

  151  sudo thinkfan -n  ## -n No daemon
  157  sudo rm /run/thinkfan.pid 

  153  sudo systemctl enable thinkfan
  154  sudo systemctl start thinkfan
  159  systemctl status thinkfan

```
Now shut down the laptop, remove the AC charging, reset the BIOS, boot, and it should be silent.
If not, try repeating (I had to do it twice as I did something improperly the first time.
```
  187  sudo systemctl restart thinkfan
  188  systemctl status thinkfan
````

**Comment by OndraZizka** [comment]
The fan levels in `/etc/thinkfan.conf`:

```yaml
#######################################################
# Thinkfan Config for Lenovo T14
#######################################################

## See:  $ find /sys/devices -type f -name "temp*_input" | sort
## and pick the one which is likely CPU - coretemp + temp1
sensors:
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon8/temp1_input

## FANS: Standard ThinkPad interface
fans:
  - tpacpi: /proc/acpi/ibm/fan

## LEVELS: [Speed_Level, Start_Temp, Stop_Temp] . Level 0 is silent/off. Level 7 is maximum.
levels:
  - [0,  0,  55]
  - [1,  50, 60]
  - [2,  55, 63]
  - [3,  60, 66]
  - [4,  63, 70]
  - [5,  67, 75]
  - [7,  72, 85]
  - ["level auto", 80, 32767]
```
