### ISSUE TITLE
Crash when sensor is unreadable

### ISSUE THREAD

**Issue by rdoursenaud** [vmatare/thinkfan#41]
I have several sensor paths declared.
Unfortunately, one (iwlwifi) is not readable since some kernel update for an undetermined reason.

When starting Thinkfan crashes with the trace below.

I'd expect it to issue warning about the unavailable sensor and continue.

```
ERROR: Unhandled std::ios_base::failure[abi:cxx11]: basic_filebuf::underflow error reading the file: iostream error.
errno = Input/output error.
Backtrace:
/usr/sbin/thinkfan(+0x37764) [0x55c6b0118764]
                                             /usr/sbin/thinkfan(thinkfan::handle_uncaught()+0x20b) [0x55c6b0119acb]
                                             /usr/lib/libstdc++.so.6(+0x8fc46) [0x7f8bfac95c46]
                                             /usr/lib/libstdc++.so.6(+0x8fc91) [0x7f8bfac95c91]
                                             /usr/lib/libstdc++.so.6(+0x8fed3) [0x7f8bfac95ed3]
                                             /usr/lib/libstdc++.so.6(std::__throw_ios_failure(char const*)+0x63) [0x7f8bfacc0a83]
                                             /usr/lib/libstdc++.so.6(std::basic_filebuf<char, std::char_traits<char> >::underflow()+0x39f) [0x7f8bfacf58bf]
                                             /usr/lib/libstdc++.so.6(std::istream::sentry::sentry(std::istream&, bool)+0x19a) [0x7f8bfad0206a]
                                             /usr/lib/libstdc++.so.6(std::istream::operator>>(int&)+0x2e) [0x7f8bfad0224e]
                                             /usr/sbin/thinkfan(thinkfan::HwmonSensorDriver::read_temps() const+0x176) [0x55c6b0108746]
                                             /usr/sbin/thinkfan(thinkfan::run(thinkfan::Config const&)+0x7d) [0x55c6b00fc6dd]
                                             /usr/sbin/thinkfan(main+0x422) [0x55c6b00fadd2]
                                             /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f8bfa6694ca]
                                             /usr/sbin/thinkfan(_start+0x2a) [0x55c6b00fb9ca]
```

```/etc/thinkfan.conf```
```
sensors:
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp1_input  # CPU Package
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp2_input  # CPU Core 0
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp3_input  # CPU Core 1
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp4_input  # CPU Core 2
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp5_input  # CPU Core 3
  - hwmon: /sys/devices/virtual/hwmon/hwmon2/temp1_input  # pch_skylake
  - hwmon: /sys/devices/virtual/hwmon/hwmon3/temp1_input  # acpitz (ACPI CPU)
#  - hwmon: /sys/devices/virtual/hwmon/hwmon4/temp1_input  # iwlwifi
  - nvidia: 01:00.0  # nVidia GPU
  - atasmart: /dev/sda  # HDD
    correction: [10]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0,  40]
  - [1, 32, 55]
  - [2, 54, 66]
  - [3, 65, 76]
  - [4, 75, 80]
  - [5, 78, 85]
  - [6, 82, 88]
  - [7, 85, 32767]
```
