### ISSUE TITLE
Hungs with wrong sensor path

### ISSUE THREAD

**Issue by diggit** [vmatare/thinkfan#72]
There were probably some changes in kernel and sensors moved to different places in hwmon hierarchy. Sensor I chose to control thinkfan was in `/sys/class/hwmon/hwmon2/`. Now, `hwmon2` is empty and sensor moved to `/sys/class/hwmon/hwmon4/`. Problem is, that thinkfan with wrong config hung at startup and only possible way to terminate it is by sending SIGKILL(9).

Expected result reporting error into log and exiting with error or running all fans at max RPM.

Happens with thinkfan release 1.0.2 and same result was with master branch ~3 days ago.

**Comment by vmatare** [comment]
Hm, cannot reproduce. Can you please post the exact config you're using?

**Comment by diggit** [comment]
Yep, here it is:
```
sensors:
  - hwmon: /sys/class/hwmon/hwmon2
    indices: [1]

fans:
  - tpacpi: /proc/acpi/ibm/fan

#
# Complex level config
#
levels:
  - speed: level auto
    upper_limit: [95]

  - speed: level disengaged
    lower_limit: [80]
    #upper_limit: [60, 60, 60]

#
# Simple level config
# meaning: [FANSPEED, LOWER_LIMIT, UPPER_LIMIT]
#
#levels:
#  - [0, 0, 50]
#  - [2, 45, 60]
```
`hwmon2` exists, but there is no `temp1_input` which moved to `hwmon4`.
