### ISSUE TITLE
 Unhandled YAML::BadSubscript: operator[] call on a scalar (key: "hwmon")

### ISSUE THREAD

**Issue by vmatare** [vmatare/thinkfan#85]
by @desdic in https://github.com/vmatare/thinkfan/issues/17#issuecomment-570144511

Maybe I'm not doing it right but I'm having problems with thinkfan finding the temperatures. I have a thinkfan.conf that works but I would really like to use the yaml options since my hardware monitors change on every boot. So I have this thinkfan.yaml
```
sensors:
  - hwmon: /sys/devices/platform/coretemp.0/hwmon
    indices: [3, 4, 1, 5, 2]

fans:
  - tp_fan /proc/acpi/ibm/fan

levels:
  - speed: 0
    lower_limit: [0, 0, 0]
    upper_limit: [59, 59, 59]

  - speed: 1
    lower_limit: [52, 52, 52]
    upper_limit: [75, 75, 75]

  - speed: 2
    lower_limit: [65, 65, 65]
    upper_limit: [78, 78, 78]

  - speed: 3
    lower_limit: [66, 66, 66]
    upper_limit: [76, 76, 76]

  - speed: 4
    lower_limit: [67, 67, 67]
    upper_limit: [82, 82, 82]

  - speed: 5
    lower_limit: [68, 68, 68]
    upper_limit: [85, 85, 85]

  - speed: 7
    lower_limit: [75, 75, 75]
    upper_limit: [32767, 32767, 32767]
```
and the error I get is
```
thinkfan -c ./thinkfan.yaml

ERROR: Unhandled YAML::BadSubscript: operator[] call on a scalar (key: "hwmon").
errno = No such file or directory.
Backtrace:
thinkfan(+0x37654) [0x561ec9680654]
thinkfan(+0x2173b) [0x561ec966a73b]
/usr/lib/libstdc++.so.6(+0xa34da) [0x7fcee979d4da]
/usr/lib/libstdc++.so.6(+0xa3537) [0x7fcee979d537]
/usr/lib/libstdc++.so.6(+0xa378e) [0x7fcee979d78e]
thinkfan(YAML::Node const YAML::Node::operator[]<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x63e) [0x561ec968e3ee]
thinkfan(YAML::convert<std::vector<YAML::wtf_ptr<thinkfan::FanDriver>, std::allocator<YAML::wtf_ptr<thinkfan::FanDriver> > > >::decode(YAML::Node const&, std::vector<YAML::wtf_ptr<thinkfan::FanDriver>, std::allocator<YAML::wtf_ptr<thinkfan::FanDriver> > >&)+0x1ad) [0x561ec968fd4d]
thinkfan(YAML::convert<YAML::wtf_ptr<thinkfan::Config> >::decode(YAML::Node const&, YAML::wtf_ptr<thinkfan::Config>&)+0x14c2) [0x561ec9684532]
thinkfan(thinkfan::Config::try_read_config(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x254) [0x561ec9670d44]
thinkfan(thinkfan::Config::read_config(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x1a) [0x561ec967193a]
thinkfan(main+0x20e) [0x561ec966b8ae]
/usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7fcee9540153]
thinkfan(_start+0x2e) [0x561ec966c3ae]

This is probably a bug. Please consider reporting this at https://github.com/vmatare/thinkfan/issues. Thanks.
Aborted (core dumped)
```
version 1.0.2.r16.7027a2d-1
