### ISSUE TITLE
/proc/acpi/ibm/fan: Unknown file format on thinkpad x220 after updating to 1.2

### ISSUE THREAD

**Issue by vmatare** [vmatare/thinkfan#99]
failure on thinkpad x220 after updating to 1.2

`thinkfan[2225]: ERROR: /proc/acpi/ibm/fan: Unknown file format.`

```
/proc/acpi/ibm/fan
status:		enabled
speed:		2936
level:		auto
commands:	level <level> (<level> is 0-7, auto, disengaged, full-speed)
commands:	enable, disable
commands:	watchdog <timeout> (<timeout> is 0 (off), 1-120 (seconds))
```
```
/etc/thinkfan.yaml
sensors:
  - hwmon: /sys/class/thermal/thermal_zone0/temp
  - tpacpi: /proc/acpi/ibm/fan   #on old config this used to be "tp_fan"
levels:
  - [0, 0, 50]
  - ["level auto", 45, 75]
  - ["level disengaged", 70, 255]
```

_Originally posted by @gogron in https://github.com/vmatare/thinkfan/issues/96#issuecomment-653821166_
